### PR TITLE
Repeat the Deploy step in Github Actions to avoid failures

### LINKED ISSUE #12: FEATURE: Repeat the Deploy step in Github Actions to avoid failures
Many of the Github Actions scripts have a Deploy step as their final step; in this final step, they deploy some content to the gh-pages branch to publish it to the Github Pages site for the repo.

These steps often fail due to contention over the gh-pages branch, and have to be manually re-run.  This slows down development, since these CI/CD failures are false alarms.

In this Issue, we wrap these steps in a Github Action that will repeat the step several times before failing after a delay.

# Example

This commit shows the before and after of this change:

https://github.com/ucsb-cs156/proj-courses/commit/bec86701b5447218ab5ac39697a5702d6b73de16

The intention is to apply this transformation to each of the workflows that uses the 

Old code:

```yml
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/site/jacoco # The folder where mvn puts the files
        clean: true # Automatically remove deleted files from the deploy branch
        target-folder: ${{env.prefix}}jacoco # The folder that we serve our files from
```

New Code:

```yml
    - name: Deploy 🚀    
      if: always() # always upload artifacts, even if tests fail
      uses: Wandalen/wretry.action@master
      with:
        action: JamesIves/github-pages-deploy-action@v4
        attempt_limit: 3
        attempt_delay: 5000
        with: |
          branch: gh-pages # The branch the action should deploy to.
          folder: target/site/jacoco # The folder where mvn puts the files
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: ${{env.prefix}}jacoco # The folder that we serve our files from
```

### PR DESCRIPTION
**Pull request by jeremiahwong704**
Closes #12 

Not much to say here. Changed some of the github actions so that when they deploy content to the github pages site for the repo, it will repeat if it fails. This prevents a delay if it fails due to false alarms, which happens often. There is no dokku deployment for this, as I changed the github actions. 

The details of what I changed are as follows:
Old code:
```
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/site/jacoco # The folder where mvn puts the files
        clean: true # Automatically remove deleted files from the deploy branch
        target-folder: ${{env.prefix}}jacoco # The folder that we serve our files from
```

New Code:

```
    - name: Deploy 🚀    
      if: always() # always upload artifacts, even if tests fail
      uses: Wandalen/wretry.action@master
      with:
        action: JamesIves/github-pages-deploy-action@v4
        attempt_limit: 3
        attempt_delay: 5000
        with: |
          branch: gh-pages # The branch the action should deploy to.
          folder: target/site/jacoco # The folder where mvn puts the files
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: ${{env.prefix}}jacoco # The folder that we serve our files from
```

Per this format.

### CODE REVIEW

**Review by ethansolomon49 — APPROVED** [review]
LGTM

File: src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java [hunk 1]
```diff
@@ -117,6 +117,13 @@ public Review postReview(
         MenuItem reviewedItem = menuItemRepository.findById(itemId).orElseThrow(
                 () -> new EntityNotFoundException(MenuItem.class, itemId)
         );
+
+        // if (review.getReviewerComments() == null) {
+        //     // review.setStatus(ModerationStatus.APPROVED);
+        // } else {
+        //     // review.setStatus(ModerationStatus.AWAITING_REVIEW);
+        // }
+
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java:126]: Commented out code does not belong in a PR targetting main, and this is not related to this PR.

File: src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java [hunk 2]
```diff
@@ -160,13 +167,16 @@ public Review editReview(@Parameter Long id, @RequestBody @Valid EditedReview in
 
         if (incoming.getReviewerComments() != null &&!incoming.getReviewerComments().trim().isEmpty()) {
             oldReview.setReviewerComments(incoming.getReviewerComments());
+            // oldReview.setStatus(ModerationStatus.AWAITING_REVIEW);
         }else{
             oldReview.setReviewerComments(null);
+            // oldReview.setStatus(ModerationStatus.APPROVED);
         }
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java:175]: Commented out code does not belong in a PR targetting main, and this is not related to this PR.

**Review by pconrad — CHANGES_REQUESTED** [review]
Please remove the commented out code, and changes to ReviewController that are unrelated to this PR.
